version: '3.8'

services:
  nginx:
    build: ./services/nginx
    ports:
      - 1337:80
    depends_on:
      - web
  web:
    build:
      context:  ./services/web
    command: gunicorn --bind 0.0.0.0:5000 app:server
    expose:
      - 5000
    env_file:
      - ./.env